# Generated by Django 4.2.23 on 2025-08-05 07:33

from django.db import migrations
import editor_js.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=editor_js.fields.EditorJSField(default=1),
            preserve_default=False,
        ),
    ]
