# Generated by Django 4.2.23 on 2025-08-05 10:25

from django.db import migrations
import editor_js.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=editor_js.fields.EditorJSField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=editor_js.fields.EditorJSField(blank=True),
        ),
    ]
